### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yackermann** [MadeByMike/html5-periodic-table#1]
In the description.
Origionally -> Originally
P.S. Thanks so much to this crazy DMCA lady for letting the whole [Russian community](https://geektimes.ru/post/249544/) know about this table. :+1: :beers:
P.S.S. I am not sexist! No sexism here. Even if you found it, its not there! ~~Go back to the kitchen.~~

**Comment by yanhaijing** [comment]
amazing, nice
