### ISSUE TITLE
Broken mozilla links

### ISSUE THREAD

**Issue by seanr** [MadeByMike/html5-periodic-table#2]
At least on the few that I tried, all of the mozilla links are broken:

https://developer.mozilla.org/en/HTML/Element/phrase_elements

I'm guesing they changed their site structure at some point?

**Comment by MadeByMike** [comment]
Probably, I havent really looked at this for a while. Since people seem to be looking at this now I guess I'd better update those links. Thanks!

**Comment by YC** [comment]
I've updated the Mozilla links. 
Please review.
I've noticed that some of the w3c links are also broken.

**Comment by MadeByMike** [comment]
Fixed in rebuild
