### ISSUE TITLE
Missing <body> tag

### ISSUE THREAD

**Issue by barakplasma** [MadeByMike/html5-periodic-table#6]
Hey Mike!

The HTML5 Element Table is missing the <body> tag despite it being part of the spec https://www.w3.org/TR/html5/sections.html#the-body-element 

<img width="1390" alt="screen shot 2017-07-06 at 18 13 41" src="https://user-images.githubusercontent.com/62937/27918198-e18fe9a6-6276-11e7-9cb0-eacb0dc23068.png">

I think it's as simple as adding data to the JSON.

**Comment by MadeByMike** [comment]
Added!
